### ISSUE TITLE
Chinese Characters Where Icons Should Be

### ISSUE THREAD

**Issue by ayman** [stardiviner/mu4e-marker-icons#1]
I installed all-the-icons and the fonts and tested they installed correctly and show in dired mode correctly using https://github.com/jtbm37/all-the-icons-dired. 

With this package and mu4e, I get Chinese characters if the `mu4e-marker-icons` are on. 

<img width="142" alt="image" src="https://user-images.githubusercontent.com/1846/105251865-28be0900-5b31-11eb-979c-f3d0f5925744.png">

I tested some values and see it (and the right font which is installed in my user dir).

<img width="419" alt="image" src="https://user-images.githubusercontent.com/1846/105252338-155f6d80-5b32-11eb-9cfa-d8efe8716253.png">

Not sure how the Chinese chars are being pulled in here.

Source Code Pro is my default face. Running on Mac Big Sur installed via brew: `GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.5.0, Carbon Version 162 AppKit 1894.5) of 2020-11-14`

**Comment by ayman** [comment]
Might be an issue with the install of `all-the-icons` as: `(all-the-icons-insert-icons-for 'material)` shows the right icon in the `*scratch*` buffer but the chinese char in the `*Messages*` buffer.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/1846/105257021-c0c0f000-5b3b-11eb-9aae-029c61e84a1c.png">

**Comment by ayman** [comment]
Answering my own issue...this came from the all-the-icons config. I had to prepend to the fontset:
```
  (set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'prepend)
```
because a CJK font was earlier in the table.   Added that to the my init.el and things work.

**Comment by stardiviner** [comment]
Glad you solved problem yourself.

**Comment by DivineDominion** [comment]
@ayman can you share the init.el snippet of yours?

**Comment by ayman** [comment]
@DivineDominion So I think this is a brute force lookup so it has to go sequentially from `1..n` which means prepending onto the fontset means it spends time going through all the icons first before it gets to characters.  That's just my _guess_ but I don't understand font-specs fully.  Anyhow, this did fix this issue:

```
(use-package all-the-icons
  :config
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
  (set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'prepend)
  (set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'prepend)
  (set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'prepend)
  (set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'prepend)
  (set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'prepend)
  (set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'prepend))
```

**Comment by DivineDominion** [comment]
@ayman Thanks for sharing! That doesn't fix the issue for me, though. Will continue to investigate. :)

**Comment by stardiviner** [comment]
@DivineDominion There are some fonts which combined most icon fonts. You can try this:

https://github.com/ryanoasis/nerd-fonts

Then replace whole `'unicode` fontset to use this font.

**Comment by ayman** [comment]
> Then replace whole `'unicode` fontset to use this font.

@stardiviner Can you share the elisp to do this?

**Comment by stardiviner** [comment]
Don't use the prepend parameter. Just use the font should work.

**Comment by ayman** [comment]
Hmm...calling 
```
(set-fontset-font t 'unicode (font-spec :family "Hack Nerd Font Mono") nil)
``` 
just brings back the Chinese characters. Can you provide a code snippet?

**Comment by stardiviner** [comment]
Set chinese character separately.

Here is my config:
```elisp
(set-fontset-font t 'symbol
                  (font-spec :family "Noto Color Emoji") nil 'prepend)

(dolist (charset '(greek
                   ;; symbol
                   ))
  (set-fontset-font nil charset
                    (font-spec :name "Symbola") nil 'prepend))

(dolist (charset '(kana han cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font) charset
                    (font-spec :family "Source Han Sans CN") nil 'append))
```
